export const SELECT_NEWS = 'SELECT_NEWS';
export const REQUEST_NEWSDET = 'REQUEST_NEWSDET';
export const RECEIVE_NEWSDET = 'RECEIVE_NEWSDET';
export const RECEIVE_NEWSDET_ERROR = 'RECEIVE_NEWSDET_ERROR';

export const REQUEST_NEWSLIST = 'REQUEST_NEWSLIST';
export const RECEIVE_NEWSLIST = 'RECEIVE_NEWSLIST';
export const RECEIVE_NEWSLIST_ERROR = 'RECEIVE_NEWSLIST_ERROR';

export const REQUEST_LATEST_TECH_NEWSLIST = 'REQUEST_LATEST_TECH_NEWSLIST';
export const RECEIVE_LATEST_TECH_NEWSLIST = 'RECEIVE_LATEST_TECH_NEWSLIST';
export const RECEIVE_LATEST_TECH_NEWSLIST_ERROR = 'RECEIVE_LATEST_TECH_NEWSLIST_ERROR';

export const REQUEST_POPULAR_NEWSLIST = 'REQUEST_POPULAR_NEWSLIST';
export const RECEIVE_POPULAR_NEWSLIST = 'RECEIVE_POPULAR_NEWSLIST';
export const RECEIVE_POPULAR_NEWSLIST_ERROR = 'RECEIVE_POPULAR_NEWSLIST_ERROR';

export const REQUEST_TESLA_NEWSLIST = 'REQUEST_TESLA_NEWSLIST';
export const RECEIVE_TESLA_NEWSLIST = 'RECEIVE_TESLA_NEWSLIST';
export const RECEIVE_TESLA_NEWSLIST_ERROR = 'RECEIVE_TESLA_NEWSLIST_ERROR';

export const REQUEST_SEARCH_NEWSLIST = 'REQUEST_SEARCH_NEWSLIST';
export const RECEIVE_SEARCH_NEWSLIST = 'RECEIVE_SEARCH_NEWSLIST';
export const RECEIVE_SEARCH_NEWSLIST_ERROR = 'RECEIVE_SEARCH_NEWSLIST_ERROR';

